<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Doctor\\Rest\\Route\\RouteCollection' => 'get1',
  'Psr\\Http\\Message\\RequestInterface' => 'get2',
);

    protected function get1()
    {
        return $this->resolveFactory(static function(): \Doctor\Rest\Route\RouteCollection {
		return (new Doctor\Rest\Route\RouteCollection)
			->add('/hello-world', \App\Controller\HelloWorldController::class)
			->add('/users', \App\Controller\UsersController::class)
			->add('/user/{id:\d+}', \App\Controller\UserController::class);
	}, 'Doctor\\Rest\\Route\\RouteCollection');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function(\Psr\Container\ContainerInterface $container): \Psr\Http\Message\RequestInterface {
		return $container->get(\Doctor\Http\RequestFactory::class)->createFromGlobals();
	}, 'Psr\\Http\\Message\\RequestInterface');
    }

}
